# -*- coding: utf-8 -*-
""".ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T8VjScFifjhFXxZUinwubToQcTCDleRl
"""

GENERATE QRCODE USING

!pip install qrcode[pil]

import qrcode

# Function to generate a QR code
def generate_qr_code(data, filename="qrcode.png"):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(data)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    img.save(filename)
    print(f"QR code saved as {filename}")

# Example :
data_to_encode = "https://www.mnmjec.ac.in/"
generate_qr_code(data_to_encode)

