# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mTxqBnO1yPfc6d6xmCKvuu47cHreLUFB

GUESS THE NUMBER GAME USING PYTHON
---


---



---
"""

import random

def guess_the_number():
    print("Welcome to Guess the Number!")

    # Generate a random number between 1 and 100
    secret_number = random.randint(1, 100)
    attempts = 0

    while True:
        try:
            # Get the player's guess
            guess = int(input("Enter your guess (1-100): "))
            attempts += 1

            # Check if the guess is correct
            if guess == secret_number:
                print(f"Congratulations! You guessed the number in {attempts} attempts.")
                break
            elif guess < secret_number:
                print("Too low. Try again.")
            else:
                print("Too high. Try again.")
        except ValueError:
            print("Invalid input. Please enter a number.")
if __name__ == "__main__":
    guess_the_number()

!pip install qrcode[pil]

import qrcode

# Function to generate a QR code
def generate_qr_code(data, filename="qrcode.png"):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(data)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    img.save(filename)
    print(f"QR code saved as {filename}")

# Example usage:
data_to_encode = "https://www.mnmjec.ac.in/"
generate_qr_code(data_to_encode)